{% set name = "Elements" %}
{% set version = "6.3.0" %}
{% set rev = "release-6.3" %}
{% set build_number = 2 %}

package:
    name: {{ name|lower }} 
    version: {{ version }} 

source:
    git_rev: {{ rev }}
    git_url: https://github.com/astrorama/Elements.git
    patches:
        - macos_path.patch          # [osx]

build:
    number: {{ build_number }}
    run_exports:
        - {{ pin_subpackage('elements', max_pin='x.x.x') }}

requirements:
    build:
        - python                             # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - libcxx<16
    host:
        - python
        - boost-cpp
        - libcxx<16
        - log4cpp >=1.1.3
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('log4cpp') }}

test:
    commands:
        - $PREFIX/bin/python `which AddElementsModule` --version

about:
    home: https://github.com/astrorama/Elements.git
    license: LGPL
    summary: Elements is a C++/Python build framework. It helps to organize the software into modules which are gathered into projects.

