{% set name = "Elements" %}
{% set version = "5.12" %}
{% set build_number = 11 %}

package:
    name: {{ name|lower }} 
    version: {{ version }} 

source:
    git_rev: {{ version }}
    git_url: https://github.com/astrorama/Elements.git
    patches:
        - macos_path.patch          # [osx]
        - arm64-apple_build.patch   # [osx]


build:
    number: {{ build_number }}
    run_exports:
        - {{ pin_subpackage('elements', max_pin='x.x.x') }}

requirements:
    build:
        - cmake >=3.0
        - make
        - {{ compiler('cxx') }}
        - python >=3.7                       # [build_platform != target_platform]
        - cross-python_{{ target_platform }} # [build_platform != target_platform]
        - cython                             # [build_platform != target_platform]
    host:
        - python
        - cython
        - boost-cpp
        - log4cpp >=1.1.3
    run:
        - {{ pin_compatible('python', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', min_pin='x.x', max_pin='x.x') }}
        - {{ pin_compatible('log4cpp') }}

test:
    commands:
        - $PREFIX/bin/python `which AddElementsModule` --version

about:
    home: https://github.com/astrorama/Elements.git
    license: LGPL
    summary: Elements is a C++/Python build framework. It helps to organize the software into modules which are gathered into projects.

